services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - botnet

  php-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-bot
    restart: unless-stopped
    volumes:
      - ./:/app          # чтобы код можно было менять без сборки
      - ./session.madeline:/app/session.madeline
    depends_on:
      - rabbitmq
    networks:
      - botnet

volumes:
  rabbitmq_data:
    driver: local

networks:
  botnet:
    driver: bridge
