services:
  php-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-bot
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - ./:/app          # чтобы код можно было менять без сборки
      - ./session.madeline:/app/session.madeline
    networks:
      - botnet
    healthcheck:
      # Проверяем: файл /tmp/bot_alive должен быть изменен менее 2 минут назад
      # Затем проверяем, что соединение с RabbitMq живое
      test:
        [
          "CMD-SHELL",
          "find /tmp/bot_alive -mmin -2 | grep . || exit 1; php -r 'fsockopen(\"rabbitmq\", 5672) || exit(1);'"
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s # Даем полминуты на старт, прежде чем проверять файл
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  botnet:
    external: true
